from django.urls import path
from . import views

urlpatterns = [
    # path('', views.home, name='home'),
    # path('patient/list/', views.patient_list, name='patient_list'),
    # path('patient/create/', views.patient_create, name='patient_create'),
    # path('patient/<int:pk>/', views.patient_detail, name='patient_detail'),
    # path('patient/<int:pk>/edit/', views.patient_edit, name='patient_edit'),
    # path('patient/<int:pk>/delete/', views.patient_delete, name='patient_delete'),
    # path('appointment/list/', views.appointment_list, name='appointment_list'),
    # path('appointment/create/', views.appointment_create, name='appointment_create'),
    # path('appointment/<int:pk>/', views.appointment_detail, name='appointment_detail'),
    # path('appointment/<int:pk>/edit/', views.appointment_edit, name='appointment_edit'),
    # path('appointment/<int:pk>/delete/', views.appointment_delete, name='appointment_delete'),
    # path('notification/list/', views.notification_list, name='notification_list'),
    # path('notification/create/', views.notification_create, name='notification_create'),
    # path('notification/<int:pk>/', views.notification_detail, name='notification_detail'),
    # path('notification/<int:pk>/edit/', views.notification_edit, name='notification_edit'),
    # path('notification/<int:pk>/delete/', views.notification_delete, name='notification_delete'),
    # path('nurse/schedule/', views.nurse_schedule, name='nurse_schedule'),
    # path('nurse/schedule/create/', views.nurse_schedule_create, name='nurse_schedule_create'),
    # path('nurse/schedule/<int:pk>/', views.nurse_schedule_detail, name='nurse_schedule_detail'),    
    # path('nurse/schedule/<int:pk>/edit/', views.nurse_schedule_edit, name='nurse_schedule_edit'),
    # path('nurse/schedule/<int:pk>/delete/', views.nurse_schedule_delete, name='nurse_schedule_delete'),
    # path('medical-record/list/', views.medical_record_list, name='medical_record_list'),
    # path('medical-record/create/', views.medical_record_create, name='medical_record_create'),
    # path('medical-record/<int:pk>/', views.medical_record_detail, name='medical_record_detail'),
    # path('medical-record/<int:pk>/edit/', views.medical_record_edit, name='medical_record_edit'),
    # path('medical-record/<int:pk>/delete/', views.medical_record_delete, name='medical_record_delete'),
    # path('medication/list/', views.medication_list, name='medication_list'),
    # path('medication/create/', views.medication_create, name='medication_create'),
    # path('medication/<int:pk>/', views.medication_detail, name='medication_detail'),
    # path('medication/<int:pk>/edit/', views.medication_edit, name='medication_edit'),
    # path('medication/<int:pk>/delete/', views.medication_delete, name='medication_delete'),
]